### ISSUE TITLE
Requirements.txt is not in pip compatible format

### ISSUE THREAD

**Issue by jwilles** [RAIVNLab/InTheWild#1]
Please see this [SO issue](https://stackoverflow.com/questions/50777849/from-conda-create-requirements-txt-for-pip3) for an overview of the issue.

Could you please update with a working pip environment?

**Comment by MattWallingford** [comment]
Hi @jwilles, thanks for letting us know about the issue. A new requirements.txt file has been uploaded that is compatible with virtualenv and Python 3.8. We appreciate your interest in the project and if you have future issues or questions about the project we will work as quickly as possible to address them.
